[package]
name = "netris"
version = "0.1.0"
authors = ["Vincent Gay <glurbi@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
uuid = { version = "0.7", features = ["v4"] }
actix = "0.7"
actix-web = "0.7"
